### ISSUE TITLE
问个问题

### ISSUE THREAD

**Issue by Bingxiusmall** [XYZscratcher/translate#1]
你说，有没有可能，我是说可能，就是while True输入超标（）

**Comment by XYZscratcher** [comment]
能不能举个例子？

**Comment by Bingxiusmall** [comment]
我之前曾经写python程序的时候输入了太多行然后输入超标了()
我就在想这个会不会输入的太多也会出问题()

**Comment by XYZscratcher** [comment]
有可能，我中午试试（

**Comment by Bingxiusmall** [comment]
最好用C++模拟自动输入(
克服程序的最好方法,就是面对程序,微笑地面对他,坚持,就是胜利!(奥利给乱入
要用程序对付程序,这样最有效!(bushi

**Comment by XYZscratcher** [comment]
shi了一下，除了有点卡，没啥问题
等会我加个判断字符串的长度的代码
